name: CI/CD Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: ls -al

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Run tests
        run: docker run my-app npm test

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: user/my-app:latest
